name: Discover Planets CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/discover-planets
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ["8.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB in Github Actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
